# Redis 服务器地址
spring:
  redis:
    host: 192.168.0.108
    #Redis 服务器连接端口
    port: 6379
    #Redis 数据库索引（默认为0）
    database: 0
    #连接超时时间（毫秒）
    timeout: 1800000
    #连接池最大连接数量（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 20
        #最大阻塞等待时间（负数表示没有限制）
        max-wait: -1
        #连接池冲最大空闲连接
        max-idle: 5
        #连接池中最小空闲连接
        min-idle: 0